### ISSUE TITLE
Please add subclasses for the string type

### ISSUE THREAD

**Issue by ateevnahar** [dxandbatista/A1-pt2#9]
Objects cannot access the String datatypes functions. to handle that similar to arrays there should be a subclass in your spec for the string datatype

**Comment by dxandbatista** [comment]
Sorry for delay, will address after I get out of class at 1:30

**Comment by dxandbatista** [comment]
Not sure what you're asking for here. Since Strings are already Objects, all Queue functions seems to work as intended when returning an Object as it could return a String as well. Why would you want Objects to access String functions? 

There were Array subclasses because of the different return types for methods (i.e. any pop function returning a bool/float/int), which made sense since it seems there was Piazza discussion against wrapper Object classes.  I believe Queues are only supposed to support Objects and Strings, so I don't see the need for a subclass unless I'm misinterpreting your request.

**Comment by ateevnahar** [comment]
closed this since although I disagree there is a lack of time.
